# Generated by Django 4.2 on 2023-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default=' ')),
                ('prodapp', models.TextField(default=' ')),
                ('category', models.CharField(choices=[('VT', 'Vitamini'), ('GG', 'Gigiena'), ('AB', 'Antibiotiki'), ('OB', 'Obezbalivaushie'), ('PT', 'Prostuda')], max_length=2)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
